package main

func catalogPart2() []seedProduct {
	source := "kenya_market_bootstrap_2026_03"
	return []seedProduct{
		{Name: "Gaviscon Liquid Peppermint 200ml", CategorySlug: "gastro-care", Description: "Current Goodlife-based reference for reflux relief liquid.", Price: 1200, Stock: 70, BrandName: "Gaviscon", GenericName: "Sodium Alginate Antacid", Strength: "", DosageForm: "Suspension", PackSize: "200ml", Unit: "bottle", ActiveIngredient: "Sodium Alginate, Sodium Bicarbonate, Calcium Carbonate", PriceSource: source},
		{Name: "Gaviscon Double Action Tabs 24s", CategorySlug: "gastro-care", Description: "Current Goodlife-based reference for double-action reflux tablets.", Price: 2195, Stock: 50, BrandName: "Gaviscon", GenericName: "Antacid Tablets", Strength: "", DosageForm: "Tablet", PackSize: "24s", Unit: "pack", ActiveIngredient: "Sodium Alginate, Sodium Bicarbonate, Calcium Carbonate", PriceSource: source},
		{Name: "Gaviscon Liquid Aniseed 150ml", CategorySlug: "gastro-care", Description: "Current Goodlife-based reference for reflux relief liquid.", Price: 2211, Stock: 45, BrandName: "Gaviscon", GenericName: "Antacid Liquid", Strength: "", DosageForm: "Suspension", PackSize: "150ml", Unit: "bottle", ActiveIngredient: "Sodium Alginate, Sodium Bicarbonate, Calcium Carbonate", PriceSource: source},
		{Name: "ORS Sachets 10s", CategorySlug: "gastro-care", Description: "Oral rehydration salts for dehydration support.", Price: 180, Stock: 100, BrandName: "ORS", GenericName: "Oral Rehydration Salts", Strength: "", DosageForm: "Sachet", PackSize: "10s", Unit: "pack", ActiveIngredient: "Glucose, Sodium Chloride, Potassium Chloride, Sodium Citrate", PriceSource: source},
		{Name: "Zinc Sulfate 20mg Tabs 10s", CategorySlug: "gastro-care", Description: "Zinc support commonly paired with ORS.", Price: 140, Stock: 90, BrandName: "Zinc", GenericName: "Zinc Sulfate", Strength: "20mg", DosageForm: "Tablet", PackSize: "10s", Unit: "pack", ActiveIngredient: "Zinc Sulfate", PriceSource: source},
		{Name: "Omeprazole 20mg Caps 14s", CategorySlug: "gastro-care", Description: "Acid suppression therapy for reflux and ulcers.", Price: 250, Stock: 80, BrandName: "Omeprazole", GenericName: "Omeprazole", Strength: "20mg", DosageForm: "Capsule", PackSize: "14s", Unit: "pack", ActiveIngredient: "Omeprazole", PriceSource: source},
		{Name: "Esomeprazole 20mg Tabs 14s", CategorySlug: "gastro-care", Description: "Proton pump inhibitor for persistent reflux symptoms.", Price: 680, Stock: 60, BrandName: "Esomeprazole", GenericName: "Esomeprazole", Strength: "20mg", DosageForm: "Tablet", PackSize: "14s", Unit: "pack", ActiveIngredient: "Esomeprazole", PriceSource: source},
		{Name: "Dulcolax Tabs 30s", CategorySlug: "gastro-care", Description: "Stimulant laxative for constipation relief.", Price: 550, Stock: 60, BrandName: "Dulcolax", GenericName: "Bisacodyl", Strength: "5mg", DosageForm: "Tablet", PackSize: "30s", Unit: "pack", ActiveIngredient: "Bisacodyl", PriceSource: source},
		{Name: "Loperamide 2mg Caps 10s", CategorySlug: "gastro-care", Description: "Diarrhea symptom control.", Price: 120, Stock: 100, BrandName: "Loperamide", GenericName: "Loperamide", Strength: "2mg", DosageForm: "Capsule", PackSize: "10s", Unit: "pack", ActiveIngredient: "Loperamide", PriceSource: source},
		{Name: "Mebeverine 135mg Tabs 20s", CategorySlug: "gastro-care", Description: "Gut spasm relief for IBS-type symptoms.", Price: 520, Stock: 60, BrandName: "Mebeverine", GenericName: "Mebeverine", Strength: "135mg", DosageForm: "Tablet", PackSize: "20s", Unit: "pack", ActiveIngredient: "Mebeverine", PriceSource: source},

		{Name: "Abidec Drops 25ml", CategorySlug: "vitamins-supplements", Description: "Current Goodlife-based reference for pediatric multivitamin drops.", Price: 3216, Stock: 40, BrandName: "Abidec", GenericName: "Multivitamin Drops", Strength: "", DosageForm: "Drops", PackSize: "25ml", Unit: "bottle", ActiveIngredient: "Multivitamin Blend", PriceSource: source},
		{Name: "Abidec Multivitamin Syrup 150ml", CategorySlug: "vitamins-supplements", Description: "Current Goodlife-based reference for multivitamin syrup.", Price: 2835, Stock: 40, BrandName: "Abidec", GenericName: "Multivitamin Syrup", Strength: "", DosageForm: "Syrup", PackSize: "150ml", Unit: "bottle", ActiveIngredient: "Multivitamin Blend", PriceSource: source},
		{Name: "C1000 Vitamin C Tabs 100s", CategorySlug: "vitamins-supplements", Description: "Current Goodlife-based reference for bulk vitamin C tablets.", Price: 2859, Stock: 50, BrandName: "C1000", GenericName: "Vitamin C", Strength: "1000mg", DosageForm: "Tablet", PackSize: "100s", Unit: "pack", ActiveIngredient: "Ascorbic Acid", PriceSource: source},
		{Name: "Health Aid Vitamin C 1500mg 30s", CategorySlug: "vitamins-supplements", Description: "Current Goodlife-based reference for high-strength vitamin C.", Price: 2168, Stock: 50, BrandName: "Health Aid", GenericName: "Vitamin C", Strength: "1500mg", DosageForm: "Tablet", PackSize: "30s", Unit: "pack", ActiveIngredient: "Ascorbic Acid", PriceSource: source},
		{Name: "Haliborange Vitamin C 1000mg Eff 20s", CategorySlug: "vitamins-supplements", Description: "Current Goodlife-based reference for effervescent vitamin C.", Price: 1449, Stock: 50, BrandName: "Haliborange", GenericName: "Vitamin C", Strength: "1000mg", DosageForm: "Effervescent Tablet", PackSize: "20s", Unit: "pack", ActiveIngredient: "Ascorbic Acid", PriceSource: source},
		{Name: "Quest Effervescent Vitamin C 1000mg 20s", CategorySlug: "vitamins-supplements", Description: "Current Goodlife-based reference for vitamin C effervescent tablets.", Price: 958, Stock: 60, BrandName: "Quest", GenericName: "Vitamin C", Strength: "1000mg", DosageForm: "Effervescent Tablet", PackSize: "20s", Unit: "pack", ActiveIngredient: "Ascorbic Acid", PriceSource: source},
		{Name: "Nat C Vitamin C Tabs 1000mg 30s", CategorySlug: "vitamins-supplements", Description: "Current Goodlife-based reference for daily vitamin C tablets.", Price: 2480, Stock: 45, BrandName: "Nat C", GenericName: "Vitamin C", Strength: "1000mg", DosageForm: "Tablet", PackSize: "30s", Unit: "pack", ActiveIngredient: "Ascorbic Acid", PriceSource: source},
		{Name: "Jamieson Chewable C 500mg plus D3 30s", CategorySlug: "vitamins-supplements", Description: "Vitamin C with D3 chewables.", Price: 996, Stock: 50, BrandName: "Jamieson", GenericName: "Vitamin C + Vitamin D3", Strength: "500mg/500IU", DosageForm: "Chewable Tablet", PackSize: "30s", Unit: "pack", ActiveIngredient: "Ascorbic Acid, Cholecalciferol", PriceSource: source},
		{Name: "Health Aid Vitamin D3 1000IU 30s", CategorySlug: "vitamins-supplements", Description: "Current Goodlife-based reference for vitamin D3 maintenance.", Price: 2220, Stock: 45, BrandName: "Health Aid", GenericName: "Vitamin D3", Strength: "1000IU", DosageForm: "Tablet", PackSize: "30s", Unit: "pack", ActiveIngredient: "Cholecalciferol", PriceSource: source},
		{Name: "Omega 3 Capsules 30s", CategorySlug: "vitamins-supplements", Description: "Daily wellness omega supplement.", Price: 1250, Stock: 45, BrandName: "Omega 3", GenericName: "Omega 3", Strength: "1000mg", DosageForm: "Capsule", PackSize: "30s", Unit: "pack", ActiveIngredient: "Fish Oil", PriceSource: source},

		{Name: "Hydrocortisone Cream 30g", CategorySlug: "dermatology", Description: "Current Goodlife-based reference for hydrocortisone skin cream.", Price: 1667, Stock: 50, BrandName: "Hydrocortisone", GenericName: "Hydrocortisone", Strength: "1%", DosageForm: "Cream", PackSize: "30g", Unit: "tube", ActiveIngredient: "Hydrocortisone", PriceSource: source},
		{Name: "Hydrocortisone Ointment 1% 15g", CategorySlug: "dermatology", Description: "Current Goodlife-based reference for hydrocortisone ointment.", Price: 517, Stock: 60, BrandName: "Hydrocortisone", GenericName: "Hydrocortisone", Strength: "1%", DosageForm: "Ointment", PackSize: "15g", Unit: "tube", ActiveIngredient: "Hydrocortisone", PriceSource: source},
		{Name: "Candid Powder 30g", CategorySlug: "dermatology", Description: "Current Goodlife-based reference for clotrimazole powder.", Price: 392, Stock: 70, BrandName: "Candid", GenericName: "Clotrimazole", Strength: "", DosageForm: "Powder", PackSize: "30g", Unit: "bottle", ActiveIngredient: "Clotrimazole", PriceSource: source},
		{Name: "Travocort Cream 10g", CategorySlug: "dermatology", Description: "Current Goodlife-based reference for anti-inflammatory antifungal cream.", Price: 740, Stock: 50, BrandName: "Travocort", GenericName: "Isoconazole + Diflucortolone", Strength: "", DosageForm: "Cream", PackSize: "10g", Unit: "tube", ActiveIngredient: "Isoconazole, Diflucortolone", RequiresPrescription: true, PriceSource: source},
		{Name: "Beclomin Ointment 15g", CategorySlug: "dermatology", Description: "Current Goodlife-based reference for steroid skin ointment.", Price: 262, Stock: 50, BrandName: "Beclomin", GenericName: "Beclometasone", Strength: "", DosageForm: "Ointment", PackSize: "15g", Unit: "tube", ActiveIngredient: "Beclometasone", RequiresPrescription: true, PriceSource: source},
		{Name: "Diprogenta Ointment 15g", CategorySlug: "dermatology", Description: "Current Goodlife-based reference for steroid-antibiotic topical.", Price: 1649, Stock: 35, BrandName: "Diprogenta", GenericName: "Betamethasone + Gentamicin", Strength: "", DosageForm: "Ointment", PackSize: "15g", Unit: "tube", ActiveIngredient: "Betamethasone, Gentamicin", RequiresPrescription: true, PriceSource: source},
		{Name: "Dermovate Cream 30g", CategorySlug: "dermatology", Description: "Potent steroid topical estimate aligned to Goodlife pricing.", Price: 1300, Stock: 35, BrandName: "Dermovate", GenericName: "Clobetasol", Strength: "0.05%", DosageForm: "Cream", PackSize: "30g", Unit: "tube", ActiveIngredient: "Clobetasol", RequiresPrescription: true, PriceSource: source},
		{Name: "Nizoral Shampoo 100ml", CategorySlug: "dermatology", Description: "Current Goodlife-based reference for ketoconazole shampoo.", Price: 4280, Stock: 30, BrandName: "Nizoral", GenericName: "Ketoconazole", Strength: "2%", DosageForm: "Shampoo", PackSize: "100ml", Unit: "bottle", ActiveIngredient: "Ketoconazole", PriceSource: source},
		{Name: "Zovirax Cream 2g", CategorySlug: "dermatology", Description: "Current Goodlife-based reference for acyclovir cream.", Price: 2415, Stock: 25, BrandName: "Zovirax", GenericName: "Acyclovir", Strength: "5%", DosageForm: "Cream", PackSize: "2g", Unit: "tube", ActiveIngredient: "Acyclovir", PriceSource: source},
		{Name: "Mebo Ointment 15g", CategorySlug: "dermatology", Description: "Current Goodlife-based reference for burn and wound topical support.", Price: 1377, Stock: 45, BrandName: "Mebo", GenericName: "Burn Ointment", Strength: "", DosageForm: "Ointment", PackSize: "15g", Unit: "tube", ActiveIngredient: "Beta-Sitosterol", PriceSource: source},

		{Name: "Dettol Liquid 500ml", CategorySlug: "first-aid", Description: "Current Goodlife-based reference for antiseptic liquid.", Price: 1925, Stock: 60, BrandName: "Dettol", GenericName: "Antiseptic Liquid", Strength: "", DosageForm: "Liquid", PackSize: "500ml", Unit: "bottle", ActiveIngredient: "Chloroxylenol", PriceSource: source},
		{Name: "Surgical Spirit 100ml", CategorySlug: "first-aid", Description: "Current Goodlife-based reference for basic first-aid antiseptic prep.", Price: 106, Stock: 80, BrandName: "Surgical Spirit", GenericName: "Surgical Spirit", Strength: "", DosageForm: "Liquid", PackSize: "100ml", Unit: "bottle", ActiveIngredient: "Methylated Spirit", PriceSource: source},
		{Name: "Crepe Bandage 2in 5cm", CategorySlug: "first-aid", Description: "Current Goodlife-based reference for small crepe bandage.", Price: 60, Stock: 100, BrandName: "Elastolite", GenericName: "Crepe Bandage", Strength: "", DosageForm: "Bandage", PackSize: "2in", Unit: "piece", ActiveIngredient: "", PriceSource: source},
		{Name: "Crepe Bandage 4in 10cm", CategorySlug: "first-aid", Description: "Current Goodlife-based reference for standard crepe bandage.", Price: 100, Stock: 100, BrandName: "Elastolite", GenericName: "Crepe Bandage", Strength: "", DosageForm: "Bandage", PackSize: "4in", Unit: "piece", ActiveIngredient: "", PriceSource: source},
		{Name: "Gauze Swabs Non Sterile 4in", CategorySlug: "first-aid", Description: "Current Goodlife-based reference for non-sterile gauze swabs.", Price: 577, Stock: 70, BrandName: "Gauze Swabs", GenericName: "Gauze Swabs", Strength: "", DosageForm: "Swab", PackSize: "4in", Unit: "pack", ActiveIngredient: "", PriceSource: source},
		{Name: "Gauze Swabs Sterile 3x3 100s", CategorySlug: "first-aid", Description: "Current Goodlife-based reference for sterile gauze swabs.", Price: 858, Stock: 60, BrandName: "Gauze Swabs", GenericName: "Sterile Gauze", Strength: "", DosageForm: "Swab", PackSize: "100s", Unit: "pack", ActiveIngredient: "", PriceSource: source},
		{Name: "Zinc Oxide Plaster 5cm x 4m", CategorySlug: "first-aid", Description: "Current Goodlife-based reference for adhesive dressing tape.", Price: 130, Stock: 80, BrandName: "Zinc Oxide Plaster", GenericName: "Surgical Tape", Strength: "", DosageForm: "Tape", PackSize: "5cm x 4m", Unit: "roll", ActiveIngredient: "", PriceSource: source},
		{Name: "Elastoplast Water Resistant Plasters 10s", CategorySlug: "first-aid", Description: "Current Goodlife-based reference for water-resistant plasters.", Price: 785, Stock: 70, BrandName: "Elastoplast", GenericName: "Plasters", Strength: "", DosageForm: "Plaster", PackSize: "10s", Unit: "pack", ActiveIngredient: "", PriceSource: source},
		{Name: "Hydrogen Peroxide 20V 200ml", CategorySlug: "first-aid", Description: "Bootstrap antiseptic estimate for wound and cleaning support.", Price: 180, Stock: 70, BrandName: "Hydrogen Peroxide", GenericName: "Hydrogen Peroxide", Strength: "20V", DosageForm: "Liquid", PackSize: "200ml", Unit: "bottle", ActiveIngredient: "Hydrogen Peroxide", PriceSource: source},
		{Name: "Ibumex Gel 25g", CategorySlug: "first-aid", Description: "Current Goodlife-based reference for topical ibuprofen gel.", Price: 120, Stock: 80, BrandName: "Ibumex", GenericName: "Ibuprofen", Strength: "", DosageForm: "Gel", PackSize: "25g", Unit: "tube", ActiveIngredient: "Ibuprofen", PriceSource: source},
	}
}
