package main

func catalogPart1() []seedProduct {
	source := "kenya_market_bootstrap_2026_03"
	return []seedProduct{
		{Name: "Cetamol 500mg Tabs 20s", CategorySlug: "pain-fever", Description: "Bootstrap Kenya-market estimate based on current Goodlife paracetamol listings.", Price: 70, Stock: 180, BrandName: "Cetamol", GenericName: "Paracetamol", Strength: "500mg", DosageForm: "Tablet", PackSize: "20s", Unit: "pack", ActiveIngredient: "Paracetamol", PriceSource: source},
		{Name: "Cetamol 500mg Tabs 100s", CategorySlug: "pain-fever", Description: "Bootstrap Kenya-market estimate aligned to current Goodlife pricing for Cetamol 100s.", Price: 286, Stock: 120, BrandName: "Cetamol", GenericName: "Paracetamol", Strength: "500mg", DosageForm: "Tablet", PackSize: "100s", Unit: "pack", ActiveIngredient: "Paracetamol", PriceSource: source},
		{Name: "Panadol Advance 500mg Tabs 16s", CategorySlug: "pain-fever", Description: "Fast-acting paracetamol for pain and fever.", Price: 210, Stock: 120, BrandName: "Panadol", GenericName: "Paracetamol", Strength: "500mg", DosageForm: "Tablet", PackSize: "16s", Unit: "pack", ActiveIngredient: "Paracetamol", PriceSource: source},
		{Name: "Panadol Extra Tabs 16s", CategorySlug: "pain-fever", Description: "Paracetamol and caffeine combination for pain relief.", Price: 240, Stock: 110, BrandName: "Panadol", GenericName: "Paracetamol + Caffeine", Strength: "500mg/65mg", DosageForm: "Tablet", PackSize: "16s", Unit: "pack", ActiveIngredient: "Paracetamol, Caffeine", PriceSource: source},
		{Name: "Brufen 400mg Tabs 20s", CategorySlug: "pain-fever", Description: "Ibuprofen tablets for pain and inflammation.", Price: 260, Stock: 100, BrandName: "Brufen", GenericName: "Ibuprofen", Strength: "400mg", DosageForm: "Tablet", PackSize: "20s", Unit: "pack", ActiveIngredient: "Ibuprofen", PriceSource: source},
		{Name: "Emzor Paracetamol Syrup 100ml", CategorySlug: "pain-fever", Description: "Pediatric pain and fever syrup.", Price: 180, Stock: 80, BrandName: "Emzor", GenericName: "Paracetamol", Strength: "120mg/5ml", DosageForm: "Syrup", PackSize: "100ml", Unit: "bottle", ActiveIngredient: "Paracetamol", PriceSource: source},
		{Name: "Buscopan 10mg Tabs 20s", CategorySlug: "pain-fever", Description: "Antispasmodic support for abdominal cramps.", Price: 580, Stock: 80, BrandName: "Buscopan", GenericName: "Hyoscine Butylbromide", Strength: "10mg", DosageForm: "Tablet", PackSize: "20s", Unit: "pack", ActiveIngredient: "Hyoscine Butylbromide", PriceSource: source},
		{Name: "Piroxicam Gel 30g", CategorySlug: "pain-fever", Description: "Topical anti-inflammatory gel for localized pain.", Price: 320, Stock: 90, BrandName: "Piroxicam", GenericName: "Piroxicam", Strength: "0.5%", DosageForm: "Gel", PackSize: "30g", Unit: "tube", ActiveIngredient: "Piroxicam", PriceSource: source},
		{Name: "Voltaren Emulgel 20g", CategorySlug: "pain-fever", Description: "Topical diclofenac gel for muscle and joint pain.", Price: 980, Stock: 70, BrandName: "Voltaren", GenericName: "Diclofenac", Strength: "1.16%", DosageForm: "Gel", PackSize: "20g", Unit: "tube", ActiveIngredient: "Diclofenac", PriceSource: source},
		{Name: "Deep Heat Rub 35g", CategorySlug: "pain-fever", Description: "Warming topical rub for muscular aches.", Price: 430, Stock: 90, BrandName: "Deep Heat", GenericName: "Topical Counterirritant", Strength: "", DosageForm: "Cream", PackSize: "35g", Unit: "tube", ActiveIngredient: "Menthol, Methyl Salicylate", PriceSource: source},

		{Name: "Amoxil 500mg Caps 100s", CategorySlug: "antibiotics", Description: "Bootstrap antibiotic estimate informed by current Goodlife Amoxil listings; actual live price should be reviewed before go-live.", Price: 380, Stock: 40, BrandName: "Amoxil", GenericName: "Amoxicillin", Strength: "500mg", DosageForm: "Capsule", PackSize: "100s", Unit: "pack", ActiveIngredient: "Amoxicillin", RequiresPrescription: true, PriceSource: source},
		{Name: "Amoxil Forte Syrup 250mg/5ml 100ml", CategorySlug: "antibiotics", Description: "Pediatric amoxicillin suspension estimate calibrated from current Goodlife listing.", Price: 838, Stock: 40, BrandName: "Amoxil", GenericName: "Amoxicillin", Strength: "250mg/5ml", DosageForm: "Suspension", PackSize: "100ml", Unit: "bottle", ActiveIngredient: "Amoxicillin", RequiresPrescription: true, PriceSource: source},
		{Name: "Azithromycin 500mg Tabs 3s", CategorySlug: "antibiotics", Description: "Short-course macrolide antibiotic.", Price: 420, Stock: 35, BrandName: "Azithromycin", GenericName: "Azithromycin", Strength: "500mg", DosageForm: "Tablet", PackSize: "3s", Unit: "pack", ActiveIngredient: "Azithromycin", RequiresPrescription: true, PriceSource: source},
		{Name: "Augmentin 625mg Tabs 16s", CategorySlug: "antibiotics", Description: "Amoxicillin-clavulanate combination antibiotic.", Price: 1450, Stock: 30, BrandName: "Augmentin", GenericName: "Amoxicillin + Clavulanate", Strength: "625mg", DosageForm: "Tablet", PackSize: "16s", Unit: "pack", ActiveIngredient: "Amoxicillin, Clavulanic Acid", RequiresPrescription: true, PriceSource: source},
		{Name: "Cefuroxime 500mg Tabs 10s", CategorySlug: "antibiotics", Description: "Second-generation cephalosporin antibiotic.", Price: 1350, Stock: 30, BrandName: "Cefuroxime", GenericName: "Cefuroxime", Strength: "500mg", DosageForm: "Tablet", PackSize: "10s", Unit: "pack", ActiveIngredient: "Cefuroxime", RequiresPrescription: true, PriceSource: source},
		{Name: "Metronidazole 400mg Tabs 28s", CategorySlug: "antibiotics", Description: "Antimicrobial for anaerobic and protozoal infections.", Price: 220, Stock: 50, BrandName: "Metronidazole", GenericName: "Metronidazole", Strength: "400mg", DosageForm: "Tablet", PackSize: "28s", Unit: "pack", ActiveIngredient: "Metronidazole", RequiresPrescription: true, PriceSource: source},
		{Name: "Flucloxacillin 500mg Caps 28s", CategorySlug: "antibiotics", Description: "Penicillin antibiotic used under pharmacist review.", Price: 480, Stock: 35, BrandName: "Flucloxacillin", GenericName: "Flucloxacillin", Strength: "500mg", DosageForm: "Capsule", PackSize: "28s", Unit: "pack", ActiveIngredient: "Flucloxacillin", RequiresPrescription: true, PriceSource: source},
		{Name: "Doxycycline 100mg Caps 14s", CategorySlug: "antibiotics", Description: "Tetracycline antibiotic.", Price: 390, Stock: 35, BrandName: "Doxycycline", GenericName: "Doxycycline", Strength: "100mg", DosageForm: "Capsule", PackSize: "14s", Unit: "pack", ActiveIngredient: "Doxycycline", RequiresPrescription: true, PriceSource: source},
		{Name: "Ciprofloxacin 500mg Tabs 10s", CategorySlug: "antibiotics", Description: "Fluoroquinolone antibiotic.", Price: 430, Stock: 30, BrandName: "Ciprofloxacin", GenericName: "Ciprofloxacin", Strength: "500mg", DosageForm: "Tablet", PackSize: "10s", Unit: "pack", ActiveIngredient: "Ciprofloxacin", RequiresPrescription: true, PriceSource: source},
		{Name: "Co-Trimoxazole Suspension 100ml", CategorySlug: "antibiotics", Description: "Trimethoprim-sulfamethoxazole pediatric suspension.", Price: 220, Stock: 35, BrandName: "Co-Trimoxazole", GenericName: "Trimethoprim + Sulfamethoxazole", Strength: "240mg/5ml", DosageForm: "Suspension", PackSize: "100ml", Unit: "bottle", ActiveIngredient: "Trimethoprim, Sulfamethoxazole", RequiresPrescription: true, PriceSource: source},

		{Name: "Benadryl One A Day Relief Tabs 7s", CategorySlug: "allergy", Description: "Current Goodlife-based reference for cetirizine allergy relief 7s pack.", Price: 1515, Stock: 60, BrandName: "Benadryl", GenericName: "Cetirizine", Strength: "10mg", DosageForm: "Tablet", PackSize: "7s", Unit: "pack", ActiveIngredient: "Cetirizine", PriceSource: source},
		{Name: "Benadryl One A Day Relief Tabs 14s", CategorySlug: "allergy", Description: "Current Goodlife-based reference for cetirizine allergy relief 14s pack.", Price: 2306, Stock: 50, BrandName: "Benadryl", GenericName: "Cetirizine", Strength: "10mg", DosageForm: "Tablet", PackSize: "14s", Unit: "pack", ActiveIngredient: "Cetirizine", PriceSource: source},
		{Name: "Cetirizine 10mg Tabs 30s", CategorySlug: "allergy", Description: "Generic antihistamine for allergic rhinitis and urticaria.", Price: 420, Stock: 80, BrandName: "Cetirizine", GenericName: "Cetirizine", Strength: "10mg", DosageForm: "Tablet", PackSize: "30s", Unit: "pack", ActiveIngredient: "Cetirizine", PriceSource: source},
		{Name: "Loratadine 10mg Tabs 10s", CategorySlug: "allergy", Description: "Non-drowsy allergy relief.", Price: 180, Stock: 80, BrandName: "Loratadine", GenericName: "Loratadine", Strength: "10mg", DosageForm: "Tablet", PackSize: "10s", Unit: "pack", ActiveIngredient: "Loratadine", PriceSource: source},
		{Name: "Piriton Syrup 150ml", CategorySlug: "allergy", Description: "Chlorpheniramine syrup for itch and allergy symptoms.", Price: 390, Stock: 70, BrandName: "Piriton", GenericName: "Chlorpheniramine", Strength: "2mg/5ml", DosageForm: "Syrup", PackSize: "150ml", Unit: "bottle", ActiveIngredient: "Chlorpheniramine", PriceSource: source},
		{Name: "Piriton Tabs 28s", CategorySlug: "allergy", Description: "Chlorpheniramine tablets for allergic symptoms.", Price: 220, Stock: 80, BrandName: "Piriton", GenericName: "Chlorpheniramine", Strength: "4mg", DosageForm: "Tablet", PackSize: "28s", Unit: "pack", ActiveIngredient: "Chlorpheniramine", PriceSource: source},
		{Name: "Telfast 120mg Tabs 10s", CategorySlug: "allergy", Description: "Fexofenadine tablets for seasonal allergies.", Price: 980, Stock: 60, BrandName: "Telfast", GenericName: "Fexofenadine", Strength: "120mg", DosageForm: "Tablet", PackSize: "10s", Unit: "pack", ActiveIngredient: "Fexofenadine", PriceSource: source},
		{Name: "Avamys Nasal Spray 120 Doses", CategorySlug: "allergy", Description: "Steroid nasal spray for persistent allergic rhinitis.", Price: 2950, Stock: 35, BrandName: "Avamys", GenericName: "Fluticasone Furoate", Strength: "27.5mcg", DosageForm: "Nasal Spray", PackSize: "120 doses", Unit: "bottle", ActiveIngredient: "Fluticasone Furoate", PriceSource: source},
		{Name: "Beconase AQ Nasal Spray", CategorySlug: "allergy", Description: "Allergy nasal spray for congestion and sneezing.", Price: 1800, Stock: 35, BrandName: "Beconase", GenericName: "Beclometasone", Strength: "50mcg", DosageForm: "Nasal Spray", PackSize: "180 doses", Unit: "bottle", ActiveIngredient: "Beclometasone", PriceSource: source},
		{Name: "Calamine Lotion 100ml", CategorySlug: "allergy", Description: "Topical itch relief for mild rashes and insect bites.", Price: 220, Stock: 90, BrandName: "Calamine", GenericName: "Calamine", Strength: "", DosageForm: "Lotion", PackSize: "100ml", Unit: "bottle", ActiveIngredient: "Calamine", PriceSource: source},

		{Name: "Benylin Dry Cough 200ml", CategorySlug: "cough-cold", Description: "Current Goodlife-based reference for dry cough syrup.", Price: 1563, Stock: 60, BrandName: "Benylin", GenericName: "Dextromethorphan", Strength: "", DosageForm: "Syrup", PackSize: "200ml", Unit: "bottle", ActiveIngredient: "Dextromethorphan", PriceSource: source},
		{Name: "Zefcolin Cough Syrup 100ml", CategorySlug: "cough-cold", Description: "Current Goodlife-based reference for dry cough and cold symptom syrup.", Price: 441, Stock: 70, BrandName: "Zefcolin", GenericName: "Dextromethorphan + Cetirizine + Phenylephrine", Strength: "", DosageForm: "Syrup", PackSize: "100ml", Unit: "bottle", ActiveIngredient: "Dextromethorphan, Cetirizine, Phenylephrine, Menthol", PriceSource: source},
		{Name: "Covonia Dry Cough Lozenges 24s", CategorySlug: "cough-cold", Description: "Soothing lozenges for throat irritation.", Price: 520, Stock: 60, BrandName: "Covonia", GenericName: "Menthol Lozenges", Strength: "", DosageForm: "Lozenge", PackSize: "24s", Unit: "pack", ActiveIngredient: "Menthol", PriceSource: source},
		{Name: "Strepsils Orange Vitamin C 36s", CategorySlug: "cough-cold", Description: "Current Goodlife-based reference for Strepsils Vitamin C throat lozenges.", Price: 1870, Stock: 60, BrandName: "Strepsils", GenericName: "Amylmetacresol + Dichlorobenzyl Alcohol + Vitamin C", Strength: "", DosageForm: "Lozenge", PackSize: "36s", Unit: "pack", ActiveIngredient: "Amylmetacresol, Dichlorobenzyl Alcohol, Vitamin C", PriceSource: source},
		{Name: "Strepsils Honey Lemon 24s", CategorySlug: "cough-cold", Description: "Classic sore-throat lozenges.", Price: 950, Stock: 60, BrandName: "Strepsils", GenericName: "Amylmetacresol + Dichlorobenzyl Alcohol", Strength: "", DosageForm: "Lozenge", PackSize: "24s", Unit: "pack", ActiveIngredient: "Amylmetacresol, Dichlorobenzyl Alcohol", PriceSource: source},
		{Name: "Vicks VapoRub 50g", CategorySlug: "cough-cold", Description: "Chest rub for congestion relief.", Price: 780, Stock: 80, BrandName: "Vicks", GenericName: "Mentholated Rub", Strength: "", DosageForm: "Ointment", PackSize: "50g", Unit: "jar", ActiveIngredient: "Menthol, Camphor, Eucalyptus Oil", PriceSource: source},
		{Name: "Sinutab Tabs 10s", CategorySlug: "cough-cold", Description: "Tablet relief for cold congestion and sinus pressure.", Price: 420, Stock: 70, BrandName: "Sinutab", GenericName: "Paracetamol + Pseudoephedrine", Strength: "", DosageForm: "Tablet", PackSize: "10s", Unit: "pack", ActiveIngredient: "Paracetamol, Pseudoephedrine", PriceSource: source},
		{Name: "Eugica Herbal Cold Flu Sachets 10s", CategorySlug: "cough-cold", Description: "Current Goodlife-based reference for herbal cold and flu support.", Price: 1190, Stock: 50, BrandName: "Eugica", GenericName: "Herbal Cold and Flu Support", Strength: "", DosageForm: "Sachet", PackSize: "10s", Unit: "pack", ActiveIngredient: "Herbal Blend", PriceSource: source},
		{Name: "Otrivin Nasal Drops 10ml", CategorySlug: "cough-cold", Description: "Nasal decongestant drops.", Price: 420, Stock: 60, BrandName: "Otrivin", GenericName: "Xylometazoline", Strength: "0.1%", DosageForm: "Drops", PackSize: "10ml", Unit: "bottle", ActiveIngredient: "Xylometazoline", PriceSource: source},
		{Name: "Menthodex Cough Syrup 100ml", CategorySlug: "cough-cold", Description: "Symptomatic relief for dry and irritating cough.", Price: 360, Stock: 60, BrandName: "Menthodex", GenericName: "Cough Syrup", Strength: "", DosageForm: "Syrup", PackSize: "100ml", Unit: "bottle", ActiveIngredient: "Dextromethorphan", PriceSource: source},
	}
}
